#!/bin/sh

# Make sure autotools are setup
if ! test -f ./configure ; then
   autoreconf --install --force --symlink
fi

# Get requested configuration
if test -n "$1" ; then
   arg=$1
else
   arg=`hostname`
fi

# Apply configuration
case $arg in
   freeze*|hush*)
       echo "Configuration: Laptop (TUBS)"
       CC="gcc" \
       LDFLAGS="-L/usr/local/lib -L/usr/local/opt/libarchive/lib" \
       CPPFLAGS="-I/usr/local/include -I/usr/local/opt/libarchive/include" \
       CFLAGS="-pedantic -pipe -O3 -g" \
       ./configure --prefix=/opt/rieck
       ;;
   compute*)
       echo "Configuration: Compute (TUBS)"
       CC="gcc" \
       LDFLAGS="" \
       CPPFLAGS="" \
       CFLAGS="-pedantic -pipe -O3 -g" \
       ./configure --prefix=$HOME/usr
       ;;
   profile|debug)
       echo "Configuration: Profiling & Debugging"
       CC="gcc" \
       LDFLAGS="-L/usr/local/opt/libarchive/lib -g -lprofiler" \
       CPPFLAGS="-I/usr/local/opt/libarchive/include" \
       CFLAGS="-g -lprofiler  -Wl,-no_pie" \
       ./configure --prefix=/opt/rieck
       ;;
   *)
       echo "Unknown system or configuration"
       exit
       ;;
esac

if test $? -gt 0 ; then
   echo "Error: Configuration failed"
   exit 1
fi

echo
echo "Done. Press <enter> to compile"
read x

# Compile
make clean
make -j 4
