#!/bin/sh

# Get requested configuration
if test -n "$1" ; then
   arg=$1
else
   arg=`hostname`
fi

# Apply configuration
case $arg in
   scarecrow*|sec01*)
       echo "Configuration: Laptop (Goettingen)"
       CC="gcc" \
       LDFLAGS="-L/usr/local/opt/libarchive/lib" \
       CPPFLAGS="-I/usr/local/opt/libarchive/include" \
       CFLAGS="-pedantic -pipe -O3 -g" \
       ./configure --prefix=/opt/rieck --enable-libarchive 
       ;;
   kindl*)
       echo "Configuration: Kindl (OpenBSD)"
       CC="egcc" \
       LDFLAGS="-L/usr/local/lib" \
       CPPFLAGS="-I/usr/local/include" \
       CFLAGS="-pedantic -pipe -O3 -g" \
       ./configure --prefix=/opt/rieck --enable-libarchive 
       ;;
   profile|debug)
       echo "Configuration: Profiling & Debugging"
       CC="gcc" \
       LDFLAGS="-L/usr/local/opt/libarchive/lib -g -ggdb -pg -lprofiler" \
       CPPFLAGS="-I/usr/local/opt/libarchive/include" \
       CFLAGS="-g -ggdb -pg -lprofiler" \
       ./configure --prefix=/opt/rieck --enable-libarchive 
       ;;
   schulle*)
       echo "Configuration: Schulle (ESX Cluster)"
       PKG_CONFIG_PATH="/usr/local/lib/pkgconfig" \
       CC="gcc" \
       CFLAGS="-pedantic -pipe -O3 -g" \
       ./configure --enable-libarchive 
       ;;
   *)    
       echo "Unknown system or configuration"
       exit
       ;;
esac

if test $? -gt 0 ; then
   echo "Error: Configuration failed"
   exit 1
fi

echo
echo "Done. Press <enter> to compile"
read x

# Compile
make clean 
make -j 4 
